apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: poc-siu-development
  name: poc-siu-development
spec:
#  replicas: 10
  selector:
    matchLabels:
      app: poc-siu
      env: development
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 1
  template:
    metadata:
      namespace: poc-siu-development
      labels:
        app: poc-siu
        env: development
    spec:
      containers:
      - name: poc-siu-development-pod
        image: registry.gurdil.fr:4443/poc-siu-dev:latest
        ports:
        - containerPort: 9000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: poc-siu-development-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poc-siu-development
  minReplicas: 1
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50















