apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: poc-siu-development
  name: poc-siu-development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poc-siu-development
  minReplicas: 20
  maxReplicas: 500
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50















